add back bmdscore job

diff --git a/.github/workflows/test-linux.yml b/.github/workflows/test-linux.yml
--- a/.github/workflows/test-linux.yml
+++ b/.github/workflows/test-linux.yml
@@ -62,6 +62,7 @@ jobs:
           cache-dependency-glob: "**/pyproject.toml"
       - name: Build pybmds
         run: |
+          # setup compiler environment
           source ./tools/ci_setup.sh
 
           # install dependencies and compile pybmds
@@ -110,4 +111,68 @@ jobs:
           path: coverage
           retention-days: 14
 
+  bmdscore:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
 
+      # --------------------------------------------------------
+      # --------------- Install C++ dependencies ---------------
+      # --------------------------------------------------------
+      - name: Cache dependencies
+        id: cache-deps
+        uses: actions/cache@v4
+        with:
+          path: vcpkg_installed
+          key: vcpkg_installed-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
+
+      - name: Acquire vcpkg
+        if: steps.cache-deps.outputs.cache-hit != 'true'
+        uses: actions/checkout@v4
+        with:
+          repository: "Microsoft/vcpkg"
+          path: vcpkg
+          ref: c9c17dcea3016bc241df0422e82b8aea212dcb93
+
+      - name: Install libraries with vcpkg.json
+        if: steps.cache-deps.outputs.cache-hit != 'true'
+        run: |
+          "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh"
+          ${{ github.workspace }}/vcpkg/vcpkg install --overlay-ports="${{ github.workspace }}/vendor/ports" --host-triplet=x64-linux-dynamic
+
+
+      # --------------------------------------------------------
+      # -------------------- Test bmdscore ---------------------
+      # --------------------------------------------------------
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.13"
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          cache-dependency-glob: "**/pyproject.toml"
+      - name: Run clang-format
+        run: |
+          uv pip install --system poethepoet clang-format==19.1.3
+          poe format-cpp
+          git diff --exit-code --compact-summary || { echo "Code formatting failed; run 'poe format-cpp'"; exit 1; }
+      - name: Build bmdscore
+        run: |
+          # setup compiler environment
+          source ./tools/ci_setup.sh
+
+          # compile bmdscore
+          mkdir -p src/build
+          cd src/build
+          cmake ..
+          make -j$(nproc)
+
+          # run tests
+          make run_tests_with_coverage
+      - uses: actions/upload-artifact@v4
+        with:
+          name: cpp-coverage
+          path: |
+            ./src/build/coverage/*
